Imports System.Data.SqlClient

Module EP_DataAdapterQueries
	'*******************************************************************

	' Sirius EasyPlayer Data Adapter functions.
	' EP_DATAADAPTERQUERIES.VB
	' Auto-generated by Sirius SQL Database Manager: May 2026
	' Copyright 2026 Sirius Software All Rights Reserved

	'*******************************************************************

	' Declare the global data adapters

	Public ServerName As String
	Public LibraryDA As SqlDataAdapter
	Public ControlDA As SqlDataAdapter

	'*******************************************************************

	' Function to return the connection string to the current database

	'*******************************************************************
	Public Function MyConnectionString() As String

		' For security purposes, and to ensure the connection string is
		' correct, use a connection string builder.

		Dim cs As New SqlConnectionStringBuilder

		'Get the server name.  The default is the old 2012 version of SQL Server Express.

		ServerName = "(LocalDB)\" & GetSetting("SiriusSoftwareGlobal", "SQLServer", "InstanceName", "v11.0")

		cs.Add("Data Source", ServerName)
		cs.Add("AttachDbFilename", Databasename)
		cs.Add("Integrated Security", True)
		cs.Add("Connect Timeout", "60")

		Return cs.ConnectionString

	End Function

	'*******************************************************************

	' Function to return the SELECT SQL command to select records
	' from the Library table.

	'*******************************************************************
	Public Function LibrarySelectCommand() As SqlCommand

		' Declare variables

		Dim Command = New SqlCommand("SELECT * FROM [dbo].[Library] ORDER BY ArtistName, AlbumName, SongName", DB)

		' Set command type

		Command.CommandType = CommandType.Text

		Return Command

	End Function

	'*******************************************************************

	' Function to return the INSERT SQL command to insert a record
	' into the Library table.

	'*******************************************************************
	Public Function LibraryInsertCommand() As SqlCommand

		' Declare variables

		Dim Command = New SqlCommand("INSERT INTO [dbo].[Library] ([HashCode],[ArtistName],[AlbumName],[SongName],[AlbumImage]) VALUES (@HashCode,@ArtistName,@AlbumName,@SongName,@AlbumImage);" & vbCrLf & " SELECT ID,HashCode,ArtistName,AlbumName,SongName,AlbumImage FROM Library WHERE (Id = SCOPE_IDENTITY())", DB)

		' Set command type

		Command.CommandType = CommandType.Text

		' Add the parameters for the insert query.

		Command.Parameters.Add("@HashCode", SqlDbType.NChar, 64, "HashCode")
		Command.Parameters.Add("@ArtistName", SqlDbType.NVarChar, 255, "ArtistName")
		Command.Parameters.Add("@AlbumName", SqlDbType.NVarChar, 255, "AlbumName")
		Command.Parameters.Add("@SongName", SqlDbType.NVarChar, 255, "SongName")
		Command.Parameters.Add("@AlbumImage", SqlDbType.NVarChar, 255, "AlbumImage")

		Return Command

	End Function

	'*******************************************************************

	' Function to return the UPDATE SQL command to update a record
	' in the Library table.

	'*******************************************************************
	Public Function LibraryUpdateCommand() As SqlCommand

		' Declare variables

		Dim Command = New SqlCommand("UPDATE [dbo].[Library] SET [HashCode]=@HashCode,[ArtistName]=@ArtistName,[AlbumName]=@AlbumName,[SongName]=@SongName,[AlbumImage]=@AlbumImage WHERE [Id]=@Id;" & vbCrLf & " SELECT ID,HashCode,ArtistName,AlbumName,SongName,AlbumImage FROM Library WHERE [Id]=@Original_Id", DB)

		' Set command type

		Command.CommandType = CommandType.Text

		' Add the parameters for the update query.

		Command.Parameters.Add("@Id", SqlDbType.Int, 4, "ID")
		Command.Parameters.Add("@Original_Id", SqlDbType.Int, 4, "ID")
		Command.Parameters.Add("@HashCode", SqlDbType.NChar, 64, "HashCode")
		Command.Parameters.Add("@ArtistName", SqlDbType.NVarChar, 255, "ArtistName")
		Command.Parameters.Add("@AlbumName", SqlDbType.NVarChar, 255, "AlbumName")
		Command.Parameters.Add("@SongName", SqlDbType.NVarChar, 255, "SongName")
		Command.Parameters.Add("@AlbumImage", SqlDbType.NVarChar, 255, "AlbumImage")


		Return Command

	End Function

	'*******************************************************************

	' Function to return the DELETE SQL command to delete a record
	' from the Library table.

	'*******************************************************************
	Public Function LibraryDeleteCommand() As SqlCommand

		' Declare variables

		Dim Command = New SqlCommand("DELETE FROM [dbo].[Library] WHERE [Id] = @Original_ID", DB)

		' Set command type

		Command.CommandType = CommandType.Text

		' Add the parameters for the delete query.

		Command.Parameters.Add("@Original_ID", SqlDbType.Int, 4, "ID")

		Return Command

	End Function

	'*******************************************************************

	' Function to return the SELECT SQL command to select records
	' from the Control table.

	'*******************************************************************
	Public Function ControlSelectCommand() As SqlCommand

		' Declare variables

		Dim Command = New SqlCommand("SELECT * FROM [dbo].[Control]", DB)

		' Set command type

		Command.CommandType = CommandType.Text

		Return Command

	End Function

	'*******************************************************************

	' Function to return the INSERT SQL command to insert a record
	' into the Control table.

	'*******************************************************************
	Public Function ControlInsertCommand() As SqlCommand

		' Declare variables

		Dim Command = New SqlCommand("INSERT INTO [dbo].[Control] ([ItemName],[Value]) VALUES (@ItemName,@Value);" & vbCrLf & " SELECT ID,ItemName,Value FROM Control WHERE (Id = SCOPE_IDENTITY())", DB)

		' Set command type

		Command.CommandType = CommandType.Text

		' Add the parameters for the insert query.

		Command.Parameters.Add("@ItemName", SqlDbType.NChar, 50, "ItemName")
		Command.Parameters.Add("@Value", SqlDbType.Text, 2147483647, "Value")

		Return Command

	End Function

	'*******************************************************************

	' Function to return the UPDATE SQL command to update a record
	' in the Control table.

	'*******************************************************************
	Public Function ControlUpdateCommand() As SqlCommand

		' Declare variables

		Dim Command = New SqlCommand("UPDATE [dbo].[Control] SET [ItemName]=@ItemName,[Value]=@Value WHERE [Id]=@Id;" & vbCrLf & " SELECT ID,ItemName,Value FROM Control WHERE [Id]=@Original_Id", DB)

		' Set command type

		Command.CommandType = CommandType.Text

		' Add the parameters for the update query.

		Command.Parameters.Add("@Id", SqlDbType.Int, 4, "ID")
		Command.Parameters.Add("@Original_Id", SqlDbType.Int, 4, "ID")
		Command.Parameters.Add("@ItemName", SqlDbType.NChar, 50, "ItemName")
		Command.Parameters.Add("@Value", SqlDbType.Text, 2147483647, "Value")


		Return Command

	End Function

	'*******************************************************************

	' Function to return the DELETE SQL command to delete a record
	' from the Control table.

	'*******************************************************************
	Public Function ControlDeleteCommand() As SqlCommand

		' Declare variables

		Dim Command = New SqlCommand("DELETE FROM [dbo].[Control] WHERE [Id] = @Original_ID", DB)

		' Set command type

		Command.CommandType = CommandType.Text

		' Add the parameters for the delete query.

		Command.Parameters.Add("@Original_ID", SqlDbType.Int, 4, "ID")

		Return Command

	End Function

	'*******************************************************************

	' Sub to initialize the global data adapters.

	'*******************************************************************
	Public Sub InitializeDataAdapters()

		LibraryDA = New SqlDataAdapter
		LibraryDA.SelectCommand = LibrarySelectCommand()
		LibraryDA.InsertCommand = LibraryInsertCommand()
		LibraryDA.UpdateCommand = LibraryUpdateCommand()
		LibraryDA.DeleteCommand = LibraryDeleteCommand()
		LibraryDA.TableMappings.Add("Library", "Table")

		ControlDA = New SqlDataAdapter
		ControlDA.SelectCommand = ControlSelectCommand()
		ControlDA.InsertCommand = ControlInsertCommand()
		ControlDA.UpdateCommand = ControlUpdateCommand()
		ControlDA.DeleteCommand = ControlDeleteCommand()
		ControlDA.TableMappings.Add("Control", "Table")

	End Sub

	'*******************************************************************

	' Sub to detach the global data adapters from the database.

	'*******************************************************************
	Public Sub DetachDataAdapters()

		LibraryDA.SelectCommand.Connection = Nothing
		LibraryDA.InsertCommand.Connection = Nothing
		LibraryDA.UpdateCommand.Connection = Nothing
		LibraryDA.DeleteCommand.Connection = Nothing
		LibraryDA.TableMappings.Clear()
		LibraryDA.Dispose()
		LibraryDS.Dispose()

		ControlDA.SelectCommand.Connection = Nothing
		ControlDA.InsertCommand.Connection = Nothing
		ControlDA.UpdateCommand.Connection = Nothing
		ControlDA.DeleteCommand.Connection = Nothing
		ControlDA.TableMappings.Clear()
		ControlDA.Dispose()
		ControlDS.Dispose()

	End Sub
End Module
