'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class EP_Theme
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sirius_EasyPlayer.EP_Theme", GetType(EP_Theme).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnClose_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnClose.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property btnClose_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("btnClose.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnColor_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnColor.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property btnColor_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("btnColor.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property btnSave_BackgroundImage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("btnSave.BackgroundImage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property btnSave_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("btnSave.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property GroupBox1_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupBox1.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property GroupBox2_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupBox2.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property GroupBox3_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupBox3.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property GroupBox4_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("GroupBox4.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Label1_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Label1.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Label2_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Label2.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Label3_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Label3.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Panel1_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Panel1.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Panel2_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Panel2.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property Panel3_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("Panel3.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Drawing.Bitmap.
    '''</summary>
    Friend Shared ReadOnly Property PictureBox1_Image() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("PictureBox1.Image", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property PictureBox1_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("PictureBox1.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton1_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton1.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton10_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton10.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton11_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton11.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton12_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton12.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton13_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton13.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton14_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton14.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton2_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton2.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton3_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton3.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton4_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton4.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton5_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton5.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton6_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton6.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton7_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton7.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton8_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton8.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized resource of type System.Boolean similar to True.
    '''</summary>
    Friend Shared ReadOnly Property RadioButton9_Locked() As Boolean
        Get
            Dim obj As Object = ResourceManager.GetObject("RadioButton9.Locked", resourceCulture)
            Return CType(obj,Boolean)
        End Get
    End Property
End Class
